image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU

skip_commits:
  files:
    - '**/*.md'
    - 'images/**/*.*'

skip_branch_with_pr: true   

before_build:
- ps: msbuild /t:restore SmimeAccountDefaults.sln
- ps: |
    $vers = & $env:UserProfile\.nuget\packages\nerdbank.gitversioning\2.0.41\tools\Get-Version.ps1
    $ver = $vers.Version
    
    # Update the ApplicationVersion in the file
    $doc = Get-Content ".\SmimeAccountDefaults\SmimeAccountDefaults.csproj"
    $doc | % { $_.Replace("1.0.2.3", "$ver") } | Set-Content ".\SmimeAccountDefaults\SmimeAccountDefaults.csproj"
    
build_script:
- ps: msbuild .\SmimeAccountDefaults\SmimeAccountDefaults.csproj /p:Configuration=Release
- ps: msbuild /t:publish .\SmimeAccountDefaults\SmimeAccountDefaults.csproj /p:Configuration=Release
after_build:
- cmd: 7z a SmimeAccountDefaults.clickonce SmimeAccountDefaults\bin\Release\app.publish\
artifacts:
- path: '*.clickonce'
deploy: off
